# Generated by Django 4.0.1 on 2022-01-13 05:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 1, 13, 5, 6, 39, 950018, tzinfo=utc)),
        ),
    ]
