# Generated by Django 4.0.1 on 2022-01-13 05:15

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_coupon_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, validators=[myapp.models.Coupon.validate_start]),
        ),
    ]
