# Generated by Django 4.0.1 on 2022-01-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_order_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='gender',
        ),
    ]
