# Generated by Django 4.0.1 on 2022-01-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_coupon_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discripsion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
