# Generated by Django 4.0.1 on 2022-01-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_coupon_discripsion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discripsion',
        ),
        migrations.AddField(
            model_name='coupon',
            name='textfile',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
